#include<iostream>
using namespace std;

void fonction(int x,int y,int a,int b,int m,int t[100][100])
{
    for(x=0;x<m;x++)
    {
        for(y=0;y<m;y++)
        {
            if(t[x][y]==1)
                a++;
            if(t[x][y]==2)
                b++;
        }
        if(a>=5)
        {
            cout<<"1";
            break;
        }
        else
            a=0;
        if(b>=5)
        {
            cout<<"2";
            break;
        }
        else
            b=0;
    }
}

int main()
{
    int i,j,n,j1=0,j2=0;
    cin>>n;
    int tab[n][n];
    for(i=0;i<n;i++)
    {
        for(j=0;j<n;j++)
        {
            cin>>tab[i][j];
        }
    }
    fonction(i,j,j1,j2,n,tab[n][n]);
    fonction(i,j,j1,j2,n,tab[n][n]);
    fonction(i,j,j1,j2,n,tab[n][n]);
    fonction(i,j,j1,j2,n,tab[n][n]);
    fonction(i,j,j1,j2,n,tab[n][n]);
    fonction(i,j,j1,j2,n,tab[n][n]);

    /*for(i=0;i<n;i++)
    {
        for(j=0;j<n;j++)
        {
            if(tab[i][j]==1)
                j1++;
            if(tab[i][j]==2)
                j2++;
        }
        if(j1>=5)
        {
            cout<<"1";
            break;
        }
        else
            j1=0;
        if(j2>=5)
        {
            cout<<"2";
            break;
        }
        else
            j2=0;
    }
    for(i=0;i<n;i++)
    {
        for(j=0;j<n;j++)
        {
            if(tab[j][i]==1)
                j1++;
            if(tab[j][i]==2)
                j2++;
        }
        if(j1>=5)
        {
            cout<<"1";
            break;
        }
        else
            j1=0;
        if(j2>=5)
        {
            cout<<"2";
            break;
        }
        else
            j2=0;
    }
    for(i=n-1;i>0;i--)
    {
        for(j=0;j<n;j++)
        {
            if(tab[i-j][j]==1)
                j1++;
            if(tab[i-j][j]==2)
                j2++;
        }
        if(j1>=5)
        {
            cout<<"1";
            break;
        }
        else
            j1=0;
        if(j2>=5)
        {
            cout<<"2";
            break;
        }
        else
            j2=0;
    }
    for(j=n-1;j>=0;j--)
    {
        for(i=0;i<n;i++)
        {
            if(tab[i][j-i]==1)
                j1++;
            if(tab[i][j-i]==2)
                j2++;
        }
        if(j1>=5)
        {
            cout<<"1";
            break;
        }
        else
            j1=0;
        if(j2>=5)
        {
            cout<<"2";
            break;
        }
        else
            j2=0;
    }
    for(i=0;i<n;i++)
    {
        for(j=n-1;j>=0;j--)
        {
            if(tab[i-j][j]==1)
                j1++;
            if(tab[i-j][j]==2)
                j2++;
        }
        if(j1>=5)
        {
            cout<<"1";
            break;
        }
        else
            j1=0;
        if(j2>=5)
        {
            cout<<"2";
            break;
        }
        else
            j2=0;
    }
    for(j=0;j<n;j++)
    {
        for(i=n-1;i>=0;i--)
        {
            if(tab[i-j][j]==1)
                j1++;
            if(tab[i-j][j]==2)
                j2++;
        }
        if(j1>=5)
        {
            cout<<"1";
            break;
        }
        else
            j1=0;
        if(j2>=5)
        {
            cout<<"2";
            break;
        }
        else
            j2=0;
        if(j==0)
        {
            cout<<"0";
        }
    }*/
    return 0;
}